# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_deploy:
    docker:
      - image: cimg/gcp:2024.08
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" > /tmp/gcloud-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
            gcloud auth configure-docker europe-southwest1-docker.pkg.dev
      - run:
          name: Set Config Project
          command: gcloud config set project wdid-api
      - run:
          name: Configure Docker
          command: gcloud auth configure-docker europe-southwest1-docker.pkg.dev
      - setup_remote_docker:
          docker_layer_caching: true # Enable layer caching for faster builds
      - store_artifacts:
          path: build_log.txt # This stores the build logs for later inspection
      - run:
          name: Build Docker Image
          command: docker build -t europe-southwest1-docker.pkg.dev/wdid-api/wdid-api/wdid-api .
      - run:
          name: Save Docker Build Logs
          command: docker build -t europe-southwest1-docker.pkg.dev/wdid-api/wdid-api/wdid-api . > build_log.txt || true
      - run:
          name: Push Docker Image
          command: docker push europe-southwest1-docker.pkg.dev/wdid-api/wdid-api/wdid-api:latest
      - run:
          name: Deploy Image to Cloud Run
          command: gcloud run deploy wdid-api --image=europe-southwest1-docker.pkg.dev/wdid-api/wdid-api/wdid-api --region=europe-southwest1 --platform=managed --allow-unauthenticated
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy-workflow:
    jobs:
      - build_and_deploy
